---
- name: OpenStack
  hosts: localhost
  gather_facts: False

  tasks:
    - name: Criando uma instância...
      os_server:
        state: present
        name: vm-azzi-teste
        image: 54db790a-760c-4862-8ceb-d809191a7418
        key_name: ansible
        timeout: 200
        flavor: 1
        auto_floating_ip: no
        nics:
          - net-id: 7afed87a-b512-4ef1-b7e9-eb1ccb56cf1e
#fim
