---
- name: OpenStack
  hosts: localhost
  vars:
    openstack_authentication:
      project_name: admin
      user_domain_name: Default
      project_domain_name: Default

  tasks:
    - name: Criando uma instância...
      os_server:
        state: present
        auth: "{{ openstack_authentication }}"
        name: ansible-sabe-criar-vm
        image: 54db790a-760c-4862-8ceb-d809191a7418
